version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: circleci/node:18.0  # CHANGE ME 1: Choose an appropriate Docker image
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            cd client
            npm install
            npm run build  # CHANGE ME 2: Add the command to install dependencies and build your project
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud