version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd client && npm install
      - run:
          name: Run tests
          command: |
            cd client
            npm test -- --json --outputFile=test-results.json || true
            cat test-results.json
      - run:
          name: Install SonarQube Scanner
          command: cd client && npm install sonarqube-scanner
      - run:
          name: Run SonarQube scan
          command: |
            cd client
            npx sonar-scanner

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build