version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd client && npm install
      - run:
          name: Run tests
          command: |
            cd client
            npm test -- --json --outputFile=test-results.json || true
            cat test-results.json
      - run:
          name: Install SonarQube Scanner
          command: cd client && npm install sonarqube-scanner
      - run:
          name: Run SonarQube scan
          command: |
            cd client
            npx sonar-scanner \
              -Dsonar.projectKey=secure-payments-portal \
              -Dsonar.organization=your_organization \
              -Dsonar.host.url=http://localhost:9000 \
              -Dsonar.login=sqp_10b43a81e3f2f089a836fbb2ad49e2584d94e4bc

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build