version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd client
            npm install
      - run:
          name: Run tests and generate coverage
          command: |
            cd client
            npm test -- --coverage
      - run:
          name: Save coverage report
          command: |
            mkdir -p coverage
            cp -r client/coverage .
      - sonarcloud/scan:
          quality_gate: false  # Add this line to ignore quality gate status
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud